version: "3.9"
services:
  frontend:
    build: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  migration:
    build: .
    command: ./wait-for-postgres.sh db python manage.py migrate
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=postgres
  backend:
    build: .
    command: ./wait-for-postgres.sh db python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    depends_on:
      - db
    environment:
      - POSTGRES_PASSWORD=postgres